import type { Metadata } from "next";
import { Rubik, Do_Hyeon } from "next/font/google";
import "./globals.css";

const rubik = Rubik({
   variable: "--font-rubik",
   subsets: ["latin"],
});
const doHyeon = Do_Hyeon({
   variable: "--font-dohyeon",
   weight: ["400"],
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${rubik.variable} ${doHyeon.variable} antialiased`}>
            {children}
         </body>
      </html>
   );
}
